package persistencesampleschool.view;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import persistencesampleschool.SchoolGroupsJDialog;
import persistencesampleschool.data.SchoolStudent;
import persistencesampleschool.data.SchoolStudents;
import persistencesampleschool.model.SchoolStudentsTableModel;

public class SchoolStudentsPanel extends javax.swing.JPanel {

    private EntityManager entityManager;
    private SchoolStudents schoolStudents;
    private SchoolStudent schoolStudentSelected;
    private SchoolStudentsTableModel schoolStudentsTableModel;
    
    private Color defaultBackgroundColor;
    
    /**
     * Creates new form SchoolStudentsPanel
     */
    public SchoolStudentsPanel() {
        initComponents();
        defaultBackgroundColor = jTableSchoolStudents.getSelectionBackground();
    }

    public void setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
        resetJTableSchoolStudents();
    }

    // Set configuration and data content for students jTable
    private void resetJTableSchoolStudents() {
        schoolStudents = new SchoolStudents();

        // Load data from database
        Query query = entityManager.createNamedQuery("SchoolStudent.findAll");
        schoolStudents.setSchoolGroupList(query.getResultList());

        // Model for JTable, assigning classgroups content
        schoolStudentsTableModel = new SchoolStudentsTableModel(schoolStudents);
        jTableSchoolStudents.setModel(schoolStudentsTableModel);  

        // Allow only one row selected
        jTableSchoolStudents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // Listen for student selection in jtable
        jTableSchoolStudents.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent event) {
                    showDetailStudentSelected();
                }
            }
        );
        
        enableEditingStudentDetail(false);
    }

    public void showDetailStudentSelected() {
        int indexSelectedRow = jTableSchoolStudents.getSelectedRow();
        if(indexSelectedRow >= 0) {
            schoolStudentSelected = schoolStudents.getSchoolStudentList().get(indexSelectedRow);
            jTextFieldName.setText(schoolStudentSelected.getName());
            jTextFieldSurnames.setText(schoolStudentSelected.getSurnames());
            jTextFieldGrade.setText(String.valueOf(schoolStudentSelected.getGrade()));
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");            
            jTextFieldDateBirth.setText(dateFormat.format(schoolStudentSelected.getDateBirth()));
        } else {
            jTextFieldName.setText("");
            jTextFieldSurnames.setText("");
            jTextFieldGrade.setText("");
        }
    }
    
    private void enableEditingStudentDetail(boolean enable) {
        jTextFieldName.setEditable(enable);
        jTextFieldSurnames.setEditable(enable);
        jTextFieldDateBirth.setEditable(enable);
        jTextFieldGrade.setEditable(enable);
        jComboBoxSchoolGroup.setEnabled(enable);
        
        jButtonSave.setEnabled(enable);
        jButtonCancel.setEnabled(enable);
        
        jButtonAddStudent.setEnabled(!enable);
        jButtonEditStudent.setEnabled(!enable);
        jButtonRemoveStudent.setEnabled(!enable);
        
        jTableSchoolStudents.setEnabled(!enable);
        if(enable) {
            jTableSchoolStudents.setSelectionBackground(Color.GRAY);
        } else {
            jTableSchoolStudents.setSelectionBackground(defaultBackgroundColor);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSchoolStudents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSurnames = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDateBirth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGrade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSchoolGroup = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonEditStudent = new javax.swing.JButton();
        jButtonRemoveStudent = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonGroups = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        jTableSchoolStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSchoolStudents);

        jLabel1.setText("Nombre:");

        jTextFieldName.setColumns(20);

        jLabel2.setText("Apellidos:");

        jTextFieldSurnames.setColumns(30);

        jLabel3.setText("Fecha Nacimiento:");

        jTextFieldDateBirth.setColumns(10);

        jLabel4.setText("Calificación expediente:");

        jTextFieldGrade.setColumns(5);

        jLabel5.setText("Grupo:");

        jComboBoxSchoolGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/add.png"))); // NOI18N
        jButtonAddStudent.setFocusable(false);
        jButtonAddStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAddStudent);

        jButtonEditStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/edit.png"))); // NOI18N
        jButtonEditStudent.setFocusable(false);
        jButtonEditStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEditStudent);

        jButtonRemoveStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/remove.png"))); // NOI18N
        jButtonRemoveStudent.setFocusable(false);
        jButtonRemoveStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRemoveStudent.setMaximumSize(new java.awt.Dimension(39, 39));
        jButtonRemoveStudent.setMinimumSize(new java.awt.Dimension(39, 39));
        jButtonRemoveStudent.setPreferredSize(new java.awt.Dimension(39, 39));
        jButtonRemoveStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRemoveStudent);
        jToolBar1.add(jSeparator1);

        jButtonGroups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/group.png"))); // NOI18N
        jButtonGroups.setFocusable(false);
        jButtonGroups.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGroups.setMaximumSize(new java.awt.Dimension(39, 39));
        jButtonGroups.setMinimumSize(new java.awt.Dimension(39, 39));
        jButtonGroups.setPreferredSize(new java.awt.Dimension(39, 39));
        jButtonGroups.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupsActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGroups);

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSurnames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxSchoolGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSurnames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSchoolGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel)
                            .addComponent(jButtonSave)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jButtonEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStudentActionPerformed
        this.getParent().setEnabled(false);
        enableEditingStudentDetail(true);
    }//GEN-LAST:event_jButtonEditStudentActionPerformed

    private void jButtonRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoveStudentActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        schoolStudentSelected.setName(jTextFieldName.getText());
        schoolStudentSelected.setSurnames(jTextFieldSurnames.getText());
        schoolStudentSelected.setDateBirth(
                Date.valueOf(jTextFieldDateBirth.getText()));
        schoolStudentSelected.setGrade(
                BigDecimal.valueOf(Double.valueOf(jTextFieldGrade.getText())));
        
        entityManager.getTransaction().begin();
        entityManager.merge(schoolStudentSelected);
        entityManager.getTransaction().commit();
        
        enableEditingStudentDetail(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        enableEditingStudentDetail(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupsActionPerformed
        SchoolGroupsJDialog schoolGroupsJDialog = new SchoolGroupsJDialog(null, true);
        schoolGroupsJDialog.getSchoolGroupsPanel1().setEntityManager(entityManager);
        schoolGroupsJDialog.setVisible(true);
    }//GEN-LAST:event_jButtonGroupsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEditStudent;
    private javax.swing.JButton jButtonGroups;
    private javax.swing.JButton jButtonRemoveStudent;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxSchoolGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableSchoolStudents;
    private javax.swing.JTextField jTextFieldDateBirth;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurnames;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
