/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persistencesampleschool.view;

import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import persistencesampleschool.data.SchoolGroups;
import persistencesampleschool.data.SchoolGroup;
import persistencesampleschool.resources.SchoolValues;
import persistencesampleschool.model.SchoolGroupsTableModel;
import persistencesampleschool.controller.SchoolIntegerCellEditor;
import persistencesampleschool.controller.SchoolStringCellEditor;

/**
 *
 * @author javier
 */
public class SchoolGroupsPanel extends javax.swing.JPanel {

    private EntityManager entityManager;
    private SchoolGroups schoolGroups;
    private SchoolGroupsTableModel schoolGroupsTableModel;
   
    /**
     * Creates new form SchoolGroupsPanel
     */
    public SchoolGroupsPanel() {
        initComponents();
    }

    public void setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
        entityManager.getTransaction().begin(); 
        resetJTableSchoolGroups();
    }

    // Set configuration and data content for class groups jTable
    private void resetJTableSchoolGroups() {
        schoolGroups = new SchoolGroups();

        // Load data from database
        Query query = entityManager.createNamedQuery("SchoolGroup.findAll");
        schoolGroups.setSchoolGroupList(query.getResultList());

        // Model for JTable, assigning classgroups content
        schoolGroupsTableModel = new SchoolGroupsTableModel(schoolGroups);
        jTableClassGroups.setModel(schoolGroupsTableModel);  

        // Allow only one row selected
        jTableClassGroups.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);        

        setEditorsJTableSchoolGroups();
    }
    
    public void setEditorsJTableSchoolGroups() {
        // Cell editor for class group name
        JTextField jTextFieldClassGroupName = new JTextField();
        jTextFieldClassGroupName.setColumns(SchoolValues.CLASS_GROUP_NAME_LENGTH);
        jTableClassGroups.getColumnModel().getColumn(0).setCellEditor(new SchoolStringCellEditor(jTextFieldClassGroupName));  

        // Cell editor for class group capacity
        jTableClassGroups.getColumnModel().getColumn(1).setCellEditor(new SchoolIntegerCellEditor(new JTextField()));  
    }

    public boolean isSchoolGroupSavePending() {
        return schoolGroupsTableModel.isSchoolGroupSavePending();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClassGroups = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCommit = new javax.swing.JButton();
        jButtonRollback = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonNewSchoolGroup = new javax.swing.JButton();
        jButtonDeleteSchoolGroup = new javax.swing.JButton();

        jTableClassGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClassGroups);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonCommit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/save.png"))); // NOI18N
        jButtonCommit.setToolTipText("Guardar");
        jButtonCommit.setFocusable(false);
        jButtonCommit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCommit.setSize(new java.awt.Dimension(44, 36));
        jButtonCommit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommitActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCommit);

        jButtonRollback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/undo.png"))); // NOI18N
        jButtonRollback.setToolTipText("Deshacer cambios");
        jButtonRollback.setFocusable(false);
        jButtonRollback.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRollback.setMaximumSize(new java.awt.Dimension(44, 36));
        jButtonRollback.setMinimumSize(new java.awt.Dimension(44, 36));
        jButtonRollback.setPreferredSize(new java.awt.Dimension(44, 36));
        jButtonRollback.setSize(new java.awt.Dimension(44, 36));
        jButtonRollback.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRollback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRollbackActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRollback);
        jToolBar1.add(jSeparator1);

        jButtonNewSchoolGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/add.png"))); // NOI18N
        jButtonNewSchoolGroup.setToolTipText("Añadir grupo");
        jButtonNewSchoolGroup.setFocusable(false);
        jButtonNewSchoolGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewSchoolGroup.setSize(new java.awt.Dimension(44, 36));
        jButtonNewSchoolGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNewSchoolGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSchoolGroupActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonNewSchoolGroup);

        jButtonDeleteSchoolGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persistencesampleschool/resources/remove.png"))); // NOI18N
        jButtonDeleteSchoolGroup.setToolTipText("Suprimir grupo");
        jButtonDeleteSchoolGroup.setFocusable(false);
        jButtonDeleteSchoolGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeleteSchoolGroup.setMaximumSize(new java.awt.Dimension(44, 36));
        jButtonDeleteSchoolGroup.setMinimumSize(new java.awt.Dimension(44, 36));
        jButtonDeleteSchoolGroup.setPreferredSize(new java.awt.Dimension(44, 36));
        jButtonDeleteSchoolGroup.setSize(new java.awt.Dimension(44, 36));
        jButtonDeleteSchoolGroup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDeleteSchoolGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSchoolGroupActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeleteSchoolGroup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewSchoolGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSchoolGroupActionPerformed
        // Create a new empty school group object
        SchoolGroup schoolGroup = new SchoolGroup();
        schoolGroups.getSchoolGroupList().add(schoolGroup);

        // Prepare object for persist
        entityManager.persist(schoolGroup);

        // Add a row in last position of JTable
        int newRowIndex = schoolGroups.getSchoolGroupList().size()-1;
        schoolGroupsTableModel.fireTableRowsInserted(newRowIndex, newRowIndex);
        jTableClassGroups.setRowSelectionInterval(newRowIndex, newRowIndex);
    }//GEN-LAST:event_jButtonNewSchoolGroupActionPerformed

    private void jButtonDeleteSchoolGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSchoolGroupActionPerformed
        // Get index of selected row
        int rowSelectedIndex = jTableClassGroups.getSelectedRow();
        if(rowSelectedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el grupo a suprimir");
        } else {
            // Convert row index in table view to index row in list,
            //      because order in table could be different to order in list
            int selectedClassGroupIndex = jTableClassGroups.convertRowIndexToModel(rowSelectedIndex);
            // Get class group from this index position in list
            SchoolGroup classGroup = schoolGroups.getSchoolGroupList().get(selectedClassGroupIndex);
            // Prepare class group to be removed from database
            entityManager.remove(classGroup);
            // Remove class group from list
            schoolGroups.getSchoolGroupList().remove(classGroup);
            // Advise to jtable that a row has been removed from list
            schoolGroupsTableModel.fireTableRowsDeleted(rowSelectedIndex, rowSelectedIndex);
        }
    }//GEN-LAST:event_jButtonDeleteSchoolGroupActionPerformed

    private void jButtonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommitActionPerformed
        // Commit current transaction and start a new transaction
        entityManager.getTransaction().commit();
        entityManager.getTransaction().begin();
        
        schoolGroupsTableModel.setSchoolGroupSavePending(false);
    }//GEN-LAST:event_jButtonCommitActionPerformed

    private void jButtonRollbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRollbackActionPerformed
        // Rollback current transaction and start a new transaction
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        
        // Refresh JTable content
        resetJTableSchoolGroups();
        
        schoolGroupsTableModel.setSchoolGroupSavePending(false);
    }//GEN-LAST:event_jButtonRollbackActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCommit;
    private javax.swing.JButton jButtonDeleteSchoolGroup;
    private javax.swing.JButton jButtonNewSchoolGroup;
    private javax.swing.JButton jButtonRollback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTableClassGroups;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
